[workspace]
resolver = "2"
members = ["src-tauri", "sync-engine"]

[workspace.package]
version = "0.2.2"
edition = "2021"

[profile.release]
opt-level = 3
lto = true
strip = true

[workspace.dependencies]
base64 = "0.21"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v7"] }
chrono = { version = "0.4", features = ["serde"] }
tracing = "0.1"
tracing-appender = "0.2"
anyhow = "1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json", "local-time"] }
tokio = { version = "1", features = ["full"] }
dirs = "5"
thiserror = "2"
yrs = "0.27"
sha2 = "0.10"
rusqlite = { version = "0.30", features = ["bundled"] }
